### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by azlaw** [iopred/bruxism#6]
Can I get more detailed install instructions please? I'm a little confused after about 2h of trying to get the bot to run.

**Comment by iopred** [comment]
What issue are you having?

**Comment by azlaw** [comment]
I'm honestly having issues installing it, I can't get the "go get github.com/iopred/bruxism/cmd/bruxism" to run

**Comment by iopred** [comment]
You'll want to start by installing go: https://golang.org/doc/install

**Comment by azlaw** [comment]
Cool, what do I do next?

**Comment by iopred** [comment]
The `go get github.com.....` command, and the rest of my install guide.

On Jul 28, 2016 6:21 PM, "azlaw" <notifications@github.com> wrote:

Cool, what do I do next?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/iopred/bruxism/issues/6#issuecomment-236070713>, or mute
the thread

**Comment by azlaw** [comment]
do I just run it through cmd?

**Comment by iopred** [comment]
Yes

**Comment by azlaw** [comment]
Cool, ty
